<?php


namespace SellMagazin\Divi;

use ET_Builder_Module_Blog;

class Suggestion_Divi_Builder_Module extends ET_Builder_Module_Blog {

	public $vb_support = 'off';

	public function init() {
		parent::init();
		$this->name   = 'Cikk ajánló';
		$this->plural = 'Cikk ajánlók';
		$this->slug   = 'sell_post_suggestion';
//		add_filter( 'et_pb_module_content', array( $this, 'replace_highlighted_background' ),10, 5 );
//		add_filter( 'et_custom_css_fields_sell_post_suggestion', array( $this, 'custom_css' ),10, 5 );
//		add_filter( 'et_default_custom_css_fields', array( $this, 'custom_css' ),10, 5 );

//		add_filter( 'et_pb_module_shortcode_attributes', array( $this, 'replace_highlighted_background' ),10, 5 );


	}

	public function get_advanced_fields_config() {
		return array(
			'background' => array(
				'options' => array(
					'background_color' => array(
						'default' => et_builder_accent_color(),
					),
				),
			),
		);
	}

	public function get_fields() {
		$fields = parent::get_fields();


//		$fields['suggestion_index'] = array(
//			'label'            => 'Ajánló sorszáma',
//			'type'             => 'text',
//			'option_category'  => 'configuration',
//			'description'      => 'Válassz, hogy hanyadik ajánlást jelenítse meg az oldalon ez a modul!',
//			'computed_affects' => array(
//				'__posts',
//			),
//			'toggle_slug'      => 'main_content',
//			'default'          => 1,
//		);
		unset( $fields['post_type'] );
		unset( $fields['use_current_loop'] );
		unset( $fields['include_categories'] );


		return $fields;
	}

	public function render( $attrs, $content = null, $render_slug ) {
		global $post, $wp_query, $wp_the_query, $suggestion_query;


//		$responsive = et_pb_responsive_options();
//		$background_color       = $responsive->get_inheritance_background_value( $this->props, 'background_color', $device, 'background', $this->fields_unprocessed );


//		print_r($this->advanced_fields['background']);
//		var_dump($responsive);
//		var_dump($this->props);
//		print_r($this->advanced_fields);
//		die();
		$this->props['use_current_loop'] = 1;
//		$this->props['background_color'] = "#ff0000";
		$suggestion_ids                  = get_post_meta( $post->ID, 'sellmagazin_suggestions', true );

		if ( is_null( $suggestion_query ) ) {
			$suggestion_query = new \WP_Query( array(
				'post_type' => 'post',
//			'post__in'       => $suggestion_ids,
				'post__in'  => [ 149, 277, 1, 28 ],
				'orderby'   => 'post__in'
			) );
		}
		$original_query = $wp_the_query;
		$wp_query       = $suggestion_query;
		$output         = parent::render( $attrs, $content, $render_slug ); // TODO: Change the autogenerated stub
		$wp_the_query   = $wp_query = $original_query;
		wp_reset_postdata();

		return $output;
	}

//	public function process_advanced_background_options( $function_name ) {
////		echo var_dump($this->props['background_color']);
////		die();
//		$this->props['background_color'] = "#FF6600";
//		return parent::process_advanced_background_options( $function_name ); // TODO: Change the autogenerated stub
//	}

function custom_css ($custom_css_default_options) {
	echo var_dump($custom_css_default_options);
	die();
	return $custom_css_default_options;
}

	function replace_highlighted_background( $props, $attrs, $render_slug, $_address, $content ) {

//		echo var_dump($props['background_color']);
//		echo '<br>';
		if ( $render_slug == 'sell_post_suggestion' ) {
//		if ( $render_slug == 'et_pb_column' ) {
//			$props['background_color'] = "#000edf";
			$props['custom_css_main_element'] = "xdsasd: 1;";
//			echo var_dump($props);
//			die();
//			echo "------------------";
//			echo $props['background_color']. "<br>";
//			echo $props['background_color']. "<br>";
		}

		return $props;
	}
}

//function post_class($class, $post_id) {
//	echo("POST CLASS WAS INVOKED HERE");
//	die();
//	\post_class($class, $post_id);
//}
