<?php


namespace SellMagazin;

use ET_Builder_Module_Blog;

class Suggestion_Divi_Builder_Module extends ET_Builder_Module_Blog {

	public function init() {
		parent::init();
		$this->name   = 'Cikk ajánló';
		$this->plural = 'Cikk ajánlók';
		$this->slug   = 'sell_post_suggestion';
	}

	public function get_fields() {
		$fields = parent::get_fields();


		$fields['suggestion_index'] = array(
			'label'            => 'Ajánló sorszáma',
			'type'             => 'text',
			'option_category'  => 'configuration',
			'description'      => 'Válassz, hogy hanyadik ajánlást jelenítse meg az oldalon ez a modul!',
			'computed_affects' => array(
				'__posts',
			),
			'toggle_slug'      => 'main_content',
			'default'          => 1,
		);
		unset( $fields['post_type'] );
		unset( $fields['posts_number'] );
		unset( $fields['include_categories'] );


		return $fields;
	}

	public static function get_blog_posts( $args = array(), $conditional_tags = array(), $current_page = array() ) {
		die(500);
		sell_log(print_r($args,true));
		sell_log(print_r($conditional_tags,true));
		sell_log(print_r($current_page,true),true);
		return parent::get_blog_posts( $args, $conditional_tags, $current_page ); // TODO: Change the autogenerated stub
	}

	public function render( $attrs, $content = null, $render_slug ) {
		global $post, $paged, $wp_query, $wp_the_query, $wp_filter, $__et_blog_module_paged;
				var_dump($wp_the_query);
				var_dump($wp_query);
//		print_r($content);
//		print_r($render_slug);
		die('render');
		return parent::render( $attrs, $content, $render_slug ); // TODO: Change the autogenerated stub

	}
}